version: "3"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./wwwroot:/home/www-data #如果不加这行就会出现 ->  issues/2
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
    php:
        image: hellomjw/php:laravel
        volumes:
            - ./wwwroot:/home/www-data
            - ./app/php7.2/conf/php.ini-development:/usr/local/etc/php/php.ini
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test123"
